server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/orange?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true

  ai:
    dashscope: # 阿里云API-KEY
      api-key: sk-713296571e144e2dbbxxxeeeeesssa
    ollama:
      base-url: http://127.0.0.1:11434
    zhipuai: # 智谱AI API-KEY
      api-key: 861f36123xxxx3ffa27f36a73f6246.TNsgggeesl2jec1

orange:
  swagger: # swagger 配置文件
    enabled: false
    name: ${spring.application.name}
  system:
    log:
      enabled: true
