spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/orange?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  cache:
    type: redis
  data:
    redis:
      host: redis-server
      port: 6379
  ai:
    vectorstore:
      milvus:
        client:
          host: milvus-server
orange:
  swagger: # swagger 配置文件
    enabled: false
    name: ${spring.application.name}
  system:
    log:
      enabled: true
    storage:
      local:
        enabled: false
      aliyun:
        enabled: true
        domain: https://orange-prod.oss-cn-chengdu.aliyuncs.com
        end-point: oss-cn-chengdu.aliyuncs.com
        bucket-name: orange
        access-key-id: xxxxxx
        access-key-secret: xxxxxx
  security:
    white-list-url:
      - /orange-system/v1.0/auth/password-encrypt
      - /orange-ai/v1.0/chat/conversation-stream
      - /orange-ai/v1.0/apps/conversation-stream
      - /sse
      - /mcp/message
